name: Refresh Search Index
on: [page_build, workflow_dispatch]

jobs:
  search:
    name: Refresh search
    runs-on: ubuntu-latest
    steps:
      - name: check status
        if: github.event_name != 'workflow_dispatch'
        run: |
          import os
          status, errormsg = os.getenv('STATUS'), os.getenv('ERROR')
          assert status == 'built', 'There was an error building the page on GitHub pages.\n\nStatus: {}\n\nError message: {}'.format(status, errormsg)
        shell: python
        env:
          STATUS: ${{ github.event.build.status }}
          ERROR: ${{ github.event.build.error.message }}
      - name: Algolia crawler creation and crawl
        if: ${{ success() }}
        uses: algolia/algoliasearch-crawler-github-actions@v1.0.10
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          crawler-name: 'metaflow-docs'
          site-url: 'https://docs.metaflow.org'
